latest_timepoint:
  day_hour_min_option:
    set_day_hour_min: true
    day: 61
    hour: 22
    min: 30
  timestamp_option:
    set_timestamp: false
    timestamp:
test_only: false
paths:
  source_table_dir: grab_data/input/
  geohash6_filename: grab_data/intermediate/geohash6.csv
  distances_filename: grab_data/intermediate/distances.csv
  traffic_df_filename: grab_data/intermediate/spatiotemporal_df.csv
  adj_mat_filename: grab_data/intermediate/adj_mat.csv
  model_dir: grab_data/model
  output_filename: grab_data/intermediate/dcrnn_predictions.npz
  pred_arr2d_filename: grab_data/intermediate/dcrnn_pred_arr2d.csv
  pred_df_filename: grab_data/intermediate/dcrnn_pred_df.csv
  pred_long_filename: grab_data/output/dcrnn_pred_output.csv
timestep_size_in_min: 15
data:
  test_samples_per_epoch: 1
  val_samples_per_epoch: 12
  train_samples_per_epoch: 60
  test_batch_size: 1
  val_batch_size: 1
  train_batch_size: 12
  target_train_samples: 1200
  add_time_in_day: true
  add_day_of_week: false
  scale: false
model:
  activation: tanh
  output_activation: tanh
  cl_decay_steps: 2000
  exclude_zeros_in_metric: true
  filter_type: dual_random_walk
  horizon: 5
  l1_decay: 0
  max_diffusion_step: 2
  num_rnn_layers: 2
  rnn_units: 64
  seq_len:
  seq_reducing:
    enable_seq_reducing: true
    seq_len_list:
    - 8
    - 96
    - 672
    - 568
  use_curriculum_learning: true
train:
  base_lr: 0.01
  dropout: 0
  epoch: 0
  epochs: 10000
  epsilon: 0.001
  lr_decay_ratio: 0.1
  max_grad_norm: 5
  max_to_keep: 100
  min_learning_rate: 2.0e-06
  optimizer: adam
  patience: 50
  steps:
  - 20
  - 30
  - 40
  - 50
  test_every_n_epochs: 10
use_cpu_only: false
log_level: DEBUG
